site_name: Kubernetes homelab
site_description: A kubernetes homelab to test some applications

# Repository
repo_url: https://github.com/thatmlopsguy/k8s-homelab
repo_name: k8s-homelab

# Navigation
nav:
  - Overview: index.md
  - Getting Started:
    - Installation: install.md
    - Architecture: architecture.md
  - Identity: identity.md
  - Catalog: catalog.md
  - Repository: repository.md
  - Portal: portal.md
  - CI/CD: pipelines.md
  - Networking: networking.md
  - Observability: observability.md
  - Compliance: compliance.md
  - Security: security.md
  - Data Streams: streams.md
  - Data Storage: storage.md
  - Cost Management: cost.md
  - Chaos Engineering: chaos_engineering.md
  - Disaster Recovery: backup.md
  - Resources:
    - Glossary: glossary.md
    - Contributing: contributing.md
    - Release Notes: releases.md
    - Roadmap: roadmap.md
    - References: references.md

# Configuration
theme:
  name: "material"
  locale: en
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      check_paths: true
